(setq custom-file "~/.emacs.d/personal/custom.el")
(load custom-file 'noerror)

(load "~/.emacs.d/personal/defuns")

;; self managed
;; ------------------

(personal 'bindings)
(personal 'c)
(personal 'diff)
(personal 'dired)
(personal 'disabled)
(personal 'env)
(personal 'flymake)
(personal 'fonts)
(personal 'my_ggtags)
(personal 'global)
(personal 'grep)
;; (personal 'ido) ;; replaced by flx-ido
(personal 'javascript)
(personal 'kbd-macros)
(personal 'mac)
(personal 'markdown-mode)
(personal 'org)
(personal 'private)
(personal 'python)
(personal 'recentf)
(personal 'rectangle)
(personal 'ri-emacs)
(personal 'ruby-mode)
(personal 'saveplace)
(personal 'scratch)
(personal 'server-mode)
(personal 'shell-mode)
(personal 'tabs)
(personal 'theme)
(personal 'tramp)
(personal 'zoom)

;; elpa managed
;; ------------------
(setq package-archives '(("gnu" . "https://elpa.gnu.org/packages/")
                         ("melpa" . "https://melpa.org/packages/")))
(package-initialize)
(when (not package-archive-contents) (package-refresh-contents))

(package 'ag)
(package 'browse-kill-ring)
(package 'bundler)
(package 'coffee-mode)
(package 'csv-mode)
(package 'direnv)
(package 'ein)
(package 'emojify)
(package 'expand-region)
(package 'feature-mode)
(package 'flx-ido)
(package 'flx-isearch)
(package 'forge)
(package 'ggtags)
(package 'go-mode)
(package 'go-projectile)
(package 'groovy-mode)
(package 'haml-mode)
(package 'htmlize)
(package 'js2-mode)
(package 'kotlin-mode)
(package 'lua-mode)
(package 'magit)
(package 'maxframe)
(package 'mo-git-blame)
(package 'motion-mode)
(package 'multiple-cursors)
(package 'powerline)
(package 'projectile)
(package 'projectile-rails)
(package 'projectile-ripgrep)
(package 'projectile-speedbar)
(package 'py-autopep8)
(package 'python-docstring)
(package 'pyvenv)
(package 'rbenv)
(package 'rg)
(package 'sass-mode)
(package 'shell-pop)
(package 'terraform-doc)
(package 'terraform-mode)
(package 'textile-mode)
(package 'yaml-mode)
(package 'yasnippet)
(package 'yasnippet-snippets)

;; submodule managed
;; ------------------
(add-to-list 'load-path "~/.emacs.d/vendor/")

;; (vendor 'ace-jump-mode) ;; unused
;; (vendor 'auctex)        ;; unused
(vendor 'feature-mode)
 ;; (vendor 'hl-line)       ;; unused
(vendor 'jekyll)
(vendor 'jsonnet-mode)
;; (vendor 'key-chord)     ;; unused
(vendor 'mode-line-bell)
(vendor 'rcodetools    'xmp)
